Updates to use vue-simplebar for scrolling, height adjustments.
AndreasPizsa/bigfarm-subscriptions pull request #6
Opened 2018-11-15 11:16 UTC by flowlabs-studio

Have a look, bro!

2018-11-15 14:41 UTC, andreaspitzer requested changes

2018-11-15 14:41 UTC, AndreasPizsa commented on src/components/big-farm.vue
> +                        <p class="x">{{ t('subscription_general_copy') }}</p>
brauchma das x?

2018-11-15 14:41 UTC, AndreasPizsa commented on src/assets/scss/components/_bigfarm-cards.scss
> +.test {
brauchma des?

2018-11-15 17:05 UTC, flowlabs-studio commented
Am 2018-11-15 15:41, schrieb Andreas Pizsa:
> @ANDREASPIZSA requested changes on this pull request.
> -------------------------
> 
> In src/components/big-farm.vue [1]:
> 
>> @@ -29,7 +29,7 @@
>                    <span class="bigfarm__fit_height" :class="{
> 'd-none': !isPageActive(1)}">
>                      <div class="row bigfarm__intro_text">
>                        <div class="col">
> -                        <p>{{ t('subscription_general_copy') }}</p>
> +                        <p class="x">{{
> t('subscription_general_copy') }}</p>
> 
> brauchma das x?
> -------------------------
> 
> In src/assets/scss/components/_bigfarm-cards.scss [2]:
> 
>> @@ -1031,10 +1031,15 @@ h5,
>    }
>  }
> 
> +.test {
> 
> brauchma des?
> 
nope, kann raus.

lg! Wolf-Dieter

2018-11-16 05:23 UTC, andreaspitzer requested changes

2018-11-16 05:23 UTC, andreaspitzer commented on src/components/big-farm.vue
> +                        <p class="x">{{ t('subscription_general_copy') }}</p>
```suggestion
                        <p>{{ t('subscription_general_copy') }}</p>
```

2018-11-16 05:24 UTC, andreaspitzer commented on src/components/big-farm.vue
> +                        <p class="x">{{ t('subscription_general_copy') }}</p>
@flowlabs-studio bitte machen & in diesen branch pushen, sonst muss ich noch einen zusätzlichen commit nachschieben :)

2018-11-16 06:04 UTC, flowlabs-studio commented
Moin! Geändert und auch noch weitere Test-Klasse entfernt. lg! Wolf

2018-11-16 12:23 UTC, merged