Refactoring, cleanup, fixes
AndreasPizsa/bigfarm-subscriptions pull request #8
Opened 2019-04-25 13:12 UTC by IgorBabkin

1. Decompose and move some components to TS
2. Delete wasting code
3. Fix bonus list table
4. Update teaser background for Enthusiast package

2019-04-25 15:05 UTC, andreaspitzer requested changes

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/enthusiast/enthusiast-subscription.vue
> +            formatCurrency(value: 'EUR' | 'USD'): string {
🤔 This would actually be `'EUR' | 'USD' | string` (if that’s a valid TS expression)

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/subscription-guide.vue
> +        public t(id: string, ...args: string[]): string {
Please extract the `t_` methods to make them available in other places, to avoid duplication.

It’s actually a `static` method

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/subscription-status.vue
> +        public t(id: string, ...args: string[]): string {
Use extracted `t` method (see earlier comment)

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/alliance/alliance-bonus-list.vue
> +        public t(id: string, ...args: string[]): string {
See similar comments below: `t` is duplicated a lot, please put it in one place and re-use.

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/alliance/allianceItemData.ts
> +export type IAllianceItemData = string[];
K, so this is actually formatting information about alliance perks.

If you wanted to make this super properly typed, then it would be

```ts
export type IAlliancePerkTextFormat = [textKey: string, prefix: string, suffix?: string]
```

(if TS allows this)

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/enthusiast/enthusiast-bonus-list.vue
>          public t(id: string, ...args: string[]): string {
re-use

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/enthusiast/enthusiast-subscription.vue
> +            formatCurrency(value: 'EUR' | 'USD'): string {
the idea behind this is that some currency codes have abbreviation signs, in this case only EUR and USD; if there's no abbreviation, the full currency code is returned.

```ts
formatCurrency('USD') // returns '$'
formatCurrency('GBP') // returns 'GBP'
```

`formatCurrency` accepts any string, not just 'EUR'  or 'USD'; the currency code come from the server and the client has no control over its content, the correct type is `string`.

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/alliance/alliance-bonus-list.vue
> +        public iconNameForItemId(id: number): string {
duplicate code

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/alliance/alliance-subscription.vue
>              iconNameForItemId(id) {
duplicate

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/enthusiast/enthusiast-subscription.vue
> +        public iconNameForItemId(id: number): string {
duplicate

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/enthusiast/enthusiast-subscription.vue
> +        public t(id: string, ...args: string[]): string {
duplicate

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/enthusiast/enthusiast-subscription.vue
> +        private itemDataForId(id: number): IEnthusiastItemData {
duplicate

2019-04-25 15:05 UTC, andreaspitzer commented on src/components/alliance/alliance-bonus-list.vue
> +        public itemDataForId(id: number): IAllianceItemData {
duplicayte

2019-04-25 15:05 UTC, AndreasPizsa commented on src/components/alliance/alliance-bonus-list.vue
> +                .filter(unique)
nah bruh

https://perf.link/#Y29uc3QgZGF0YSA9IFsuLi5BcnJheSgxMDAwMCkua2V5cygpXQ==/W3siY29kZSI6ImNvbnN0IHVuaXF1ZSA9IChlbCwgaW5kZXgsIGFycikgPT4gYXJyLmluZGV4T2YoZWwpID09PSBpbmRleDtcbmRhdGEuZmlsdGVyKHVuaXF1ZSkiLCJlcnJvciI6ZmFsc2UsIm1lZGlhbiI6NjUuNDYwMDAwMDEyNTM1Nn0seyJjb2RlIjoiQXJyYXkuZnJvbShuZXcgU2V0KGRhdGEpKSIsImVycm9yIjpmYWxzZSwibWVkaWFuIjoxLjc1MDAwMDAxMDM2MDk2MzZ9XQ==

2019-04-25 15:05 UTC, AndreasPizsa commented on src/components/alliance/alliance-bonus-list.vue
> +                .filter(unique);
go back to `Set`

2019-04-25 15:05 UTC, AndreasPizsa commented on src/components/enthusiast/enthusiast-bonus-list.vue
> +    import {unique} from "@/core/helpers";
unique is bad :)

2019-04-25 15:05 UTC, AndreasPizsa commented on src/components/alliance/alliance-bonus-list.vue
> +    import {unique} from "@/core/helpers";
remove

2019-04-26 09:03 UTC, IgorBabkin commented on src/components/alliance/allianceItemData.ts
> +export type IAllianceItemData = string[];
Good idea, but we can only do like that `export type IAlliancePerkTextFormat = [string, string, string?];`

2019-04-26 09:07 UTC, IgorBabkin commented on src/components/alliance/alliance-bonus-list.vue
> +        public itemDataForId(id: number): IAllianceItemData {
kmon) it's duplicated in 2 files. just one line more)

2019-04-26 11:55 UTC, merged